### ISSUE TITLE
[Feature Request] Parse custom tags files

### ISSUE THREAD

**Issue by jeromedalbert** [unused-code/unused#28]
I like to name my tags file `.tags` on my projects, so it doesn't show in `ls`. For example I have it configured in Vim with `set tags=./.tags;`.

Would it be possible to parse custom tags files, maybe with an option to specify a custom file?

**Comment by joshuaclayton** [comment]
@jeromedalbert yes, I think this should be possible; if you have experience in Rust (or are interested in learning), is this something you'd want to tackle? No worries if the answer is "no" 😄 , but I've been offering in case folks are interested.

**Comment by jeromedalbert** [comment]
I have no Rust experience unfortunately, I’m more of a Ruby person 😅

**Comment by julianrubisch** [comment]
I guess it would boil down to making

https://github.com/unused-code/unused/blob/1b1f1ca097f7d3c3f2d4c1f0c8c3de9f2e03103e/crates/read_ctags/src/tags_reader.rs#L86

more configurable?

**Comment by joshuaclayton** [comment]
@jeromedalbert @julianrubisch I've gone ahead and cut version 0.4.0 of unused, which allows you to provide a custom path to the tags file; if you follow the [upgrade instructions](https://github.com/unused-code/unused#updating), you'll be able to use the flag introduced in https://github.com/unused-code/unused/pull/45 🎉

**Comment by julianrubisch** [comment]
Awesome! Thanks!

**Comment by jeromedalbert** [comment]
Thank you so much!
