### ISSUE TITLE
Add a brief snippet on non-MacOS installation/building

### ISSUE THREAD

**Issue by timon** [unused-code/unused#29]
For those of us who run Linux, there is no reference on unused.codes or here in README how to obtain/build the tool that looks very promising.

I guess I *could* have use it, but I don't know why or what tools I need to get it run locally.

**Comment by joshuaclayton** [comment]
@timon thanks for highlighting this; would you be interested in adding a section on this within the repo?

I'd expect we could:

* Link folks to the latest release: https://github.com/unused-code/unused/releases/latest
* Suggest downloading the linux/musl gzipped file
* Once unpacked, move the corresponding binary to whatever preferred directory they have that's present in `$PATH`

Does that set of steps make sense to you? Anything I missed? At minimum, confirmation on your end that those steps work would be helpful, as I could also update the docs.

Let me know what you think!

**Comment by timon** [comment]
Yes, just providing link to binary release and telling people to add binary to a folder in their `$PATH` would be suffucient

Sorry for the delayed reply

**Comment by ShockwaveNN** [comment]
@joshuaclayton Older variant of  `unused` provide a docker variant, for me it was the best way to use any program

**Comment by joshuaclayton** [comment]
Thanks @timon – I've gone ahead and opened #33 to help here.
