### ISSUE TITLE
Tag file not found

### ISSUE THREAD

**Issue by ihatemornings** [unused-code/unused#30]
I just installed `unused` using `brew install unused` and `ctags` using `brew install ctags`.

Here’s the `unused` version info:
```
> brew info unused
unused-code/formulae/unused: stable 0.2.0
Identify potentially unused code
https://unused.codes
/usr/local/Cellar/unused/0.2.0 (10 files, 3.4MB) *
  Built from source on 2021-02-04 at 12:58:04
From: https://github.com/unused-code/homebrew-formulae/blob/HEAD/Formula/unused.rb
==> Dependencies
Build: cmake ✔, rust ✔
```

And the `ctags` version info:
```
> brew info ctags
ctags: stable 5.8 (bottled), HEAD
Reimplementation of ctags(1)
https://ctags.sourceforge.io/
/usr/local/Cellar/ctags/5.8_2 (9 files, 360.0KB) *
  Poured from bottle on 2021-02-04 at 13:12:15
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/ctags.rb
```

`ctags` seemed to work ok, creating a big old file of tags at ./tags:
```
> ctags -f tags -R .
```

The top of the tag file looks like this:
```
!_TAG_FILE_FORMAT       2       /extended format; --format=1 will not append ;" to lines/
!_TAG_FILE_SORTED       1       /0=unsorted, 1=sorted, 2=foldcase/
!_TAG_PROGRAM_AUTHOR    Darren Hiebert  /dhiebert@users.sourceforge.net/
!_TAG_PROGRAM_NAME      Exuberant Ctags //
!_TAG_PROGRAM_URL       http://ctags.sourceforge.net    /official site/
!_TAG_PROGRAM_VERSION   5.8     //
```

But `unused` can’t find the tag file:
```
> unused
Failed to parse tags

Uh oh!

It looks there's an issue with your ctags file; either it doesn't exist, or the formatting is off.

Ensure you've installed Universal Ctags (https://ctags.io/) and re-run it within your application.

Error:
Unable to find ctags file (searched in ): No file provided
```

`unused doctor` gives me this:
```
> unused doctor
Unused Doctor

[Error] Check: Is the tags file not present in the list of files searched?
     Unable to find ctags file (searched in ): No file provided
[Error] Check: Are tokens found in the application?
     Unable to find ctags file (searched in ): No file provided
[Warning] Check: Are files found in the application?
     0 file(s) found
[Error] Check: Is the tags file generated with Universal Ctags?
     Could not determine tags program name
[OK] Check: Does the loaded configuration have available project types?
     Loaded the following project configurations: Rails, Phoenix

Outcome: 1 OK, 1 warnings, 3 errors
```

From what I can make out in the source code, having a file at ./tags should work fine, and it seems maybe suspcious that `(searched in )` isn’t displaying a list of possible tag file locations.

**Comment by ihatemornings** [comment]
(I’m on MacOS 10.15.7)

**Comment by joshuaclayton** [comment]
@ihatemornings hmm, interesting! `unused` not finding any files is odd to me; is this a brand new repo or have files been committed via git? `unused` honors `.gitignore`s, which plays out in two ways: it skips things like `node_modules/` to limit scope of search, and if a `tags` file gets committed, it'll likely not find anything (because it'll count from the source and the tags file, resulting in there being enough occurrences that it thinks everything's being used enough).

Excited to hear what you find!

**Comment by jeromedalbert** [comment]
One of the errors mentioned in your `unused doctor` output is that you're not using Universal Ctags. So uninstall your current ctags, and install universal-ctags, 

```
brew tap universal-ctags/universal-ctags
brew install universal-ctags
```

**Comment by ihatemornings** [comment]
@jeromedalbert I installed `universal-ctags` and recreated the tags file, but it didn’t fix the problem. I imagine it would have become a problem once I get `unused` to find the tags file though, so thanks anyway!

@joshuaclayton The directory isn’t actually a git repo at all (it’s svn) – is git a requirement?

**Comment by joshuaclayton** [comment]
@ihatemornings ah, interesting!

Indirectly, yes. The way unused retrieves the list of files is currently dependent on git (behind the scenes, it's using `git ls-files`) I'll have to look into other options to accommodate, but that's definitely what you're running into right now. I'll create another issue.

**Comment by joshuaclayton** [comment]
@ihatemornings alright – I've gone ahead and created a new issue to track the coupling to `git` here: https://github.com/unused-code/unused/issues/31

**Comment by ihatemornings** [comment]
Ah, got it. Thanks.
