### ISSUE TITLE
M1 Mac directions fail

### ISSUE THREAD

**Issue by brandondrew** [unused-code/unused#47]
After trying to fix my installation with the following steps

```
brew uninstall unused
brew untap unused-code/formulae
brew tap unused-code/formulae
brew install unused --without-mimalloc
```

I got `Error: invalid option: --without-mimalloc`.

The only similar options I see are `--with-mimalloc`.

**Comment by brandondrew** [comment]
I assume the default has changed to support M1 Macs by default, and the only thing needed here is to update the README.

**Comment by Jonic** [comment]
@brandondrew I just ran into this - looks like you're right: https://github.com/unused-code/homebrew-formulae/commit/a487468f4e14369311b3b464eb392c976b5f2db4 - the default is now to build it assuming it's running on Apple Silicon, with the option to build it for Intel-based Macs. So you're right that the README needs an update.

**Comment by Mayurifag** [comment]
I wanted to create the same issue, got same exact problem, seems to be easy fixed.

**Comment by joshuaclayton** [comment]
@brandondrew @Jonic @Mayurifag anyone interested in opening a PR with your proposed changes?

**Comment by brandondrew** [comment]
@joshuaclayton Sure, I just opened a PR: #49

**Comment by joshuaclayton** [comment]
This has been resolved via https://github.com/unused-code/unused/pull/49
